itwac_map = {
             "ADJ": "ADJ",
             "DET": "ADJ",
             "PRE": "ADP",
             "ADV": "ADV",
             "NEG": "ADV",
             "AUX": "AUX",
             "CON": "CCONJ",
             "ART": "DET",
             "ARTPRE": "DET",
#             "": "INTJ",
             "NOUN": "NOUN",
             "NUM": "NUM",
#             "": "PART",
             "PRO": "PRON",
             "CLI": "PRON",
             "NPR": "PROPN",
             "PUN": "PUNCT",
             "SENT": "PUNCT",
             "CHE": "SCONJ",
             "WH": "SCONJ",
#             "": "SYM",
             "VER": "VERB",
             "VER2": "VERB",
             "NOCAT": "X"
            }


repubblica_map = {
             "A": "ADJ",
             "E": "ADP",
             "EA": "DET",
             "DD": "DET",
             "DI": "DET",
             "DE": "DET",
             "DQ": "DET",
             "DR": "DET",
             "B": "ADV",
             "T": "ADV",
             "VA": "AUX",
             "CC": "CCONJ",
             "R": "DET",
             "I": "INTJ",
             "S": "NOUN",
             "SA": "NOUN",
             "N": "NUM",
#             "": "PART",
             "P": "PRON",
             "SP": "PROPN",
             "F": "PUNCT",
             "CS": "SCONJ",
#             "": "SYM",
             "V": "VERB",
             "X": "X"
            }


xlime_map = {
             "ADJ": "ADJ",
             "ADP": "ADP",
             "DETERMINER": "DET",
             "ADV": "ADV",
            #  "": "AUX",
             "CONJ": "CCONJ",
             "INTERJECTION": "INTJ",
             "NOUN": "NOUN",
             "NUM": "NUM",
             "PRT": "PART",
             "PRON": "PRON",
            #  "": "PROPN",
             ".": "PUNCT",
            #  "": "SCONJ",
#             "": "SYM",
             "VERB": "VERB",
             "X": "X",
             "U": "X",
             "@": "X",
             "#": "X",
             "~": "X",
             "E": "X"
            }


wikiCoNLL_map = {
    "F": "PUNCT",
    "S": "NOUN",
    "R": "DET",
    "E": "ADP",
    "A": "ADJ",
    "V": "VERB",
    "B": "ADV",
    "D": "DET",
    "C": "CCONJ",
    "P": "PRON",
    "N": "NUM",
    "X": "X",
    "T": "DET",
    "I": "INTJ"
}